// *****************************************************************************
//
// Copyright (c) 2024, Southwest Research Institute (SwRI)
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Southwest Research Institute (SwRI) nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// *****************************************************************************

#ifndef MAPVIZ_MAVROS_PLUGINS__WAYPOINT_LIST_PLUGIN_H_
#define MAPVIZ_MAVROS_PLUGINS__WAYPOINT_LIST_PLUGIN_H_

#include <mapviz/mapviz_plugin.h>

// QT libraries
#include <QGLWidget>
#include <QObject>
#include <QWidget>

// ROS libraries
#include <mapviz/map_canvas.h>
#include <rmw/types.h>

#include <mavros_msgs/msg/waypoint.hpp>
#include <mavros_msgs/msg/waypoint_list.hpp>
#include <rclcpp/rclcpp.hpp>
#include <tf2/transform_datatypes.hpp>

// C++ standard libraries
#include <mutex>
#include <string>
#include <vector>

// QT autogenerated files
#include "ui_waypoint_list_config.h"

namespace mapviz_mavros_plugins {

struct TransformedWaypoint {
  tf2::Vector3 point;
  tf2::Vector3 transformed_point;
  bool transformed;
  bool is_current;
  uint16_t command;
  uint16_t seq;
};

class WaypointListPlugin : public mapviz::MapvizPlugin {
  Q_OBJECT

 public:
  WaypointListPlugin();
  ~WaypointListPlugin() override = default;

  bool Initialize(QGLWidget* canvas) override;
  void Shutdown() override {}

  void Draw(double x, double y, double scale) override;
  void Transform() override;

  void LoadConfig(const YAML::Node& node, const std::string& path) override;
  void SaveConfig(YAML::Emitter& emitter, const std::string& path) override;

  QWidget* GetConfigWidget(QWidget* parent) override;

 protected:
  void PrintError(const std::string& message) override;
  void PrintInfo(const std::string& message) override;
  void PrintWarning(const std::string& message) override;

 protected Q_SLOTS:
  void SelectTopic();
  void TopicEdited();
  void DrawIcon();

 private:
  Ui::waypoint_list_config ui_;
  QWidget* config_widget_;

  std::string topic_;
  rmw_qos_profile_t qos_;

  rclcpp::Subscription<mavros_msgs::msg::WaypointList>::SharedPtr waypoint_sub_;
  bool has_message_;

  std::vector<TransformedWaypoint> waypoints_;
  mutable std::mutex waypoints_mutex_;
  uint16_t current_seq_;
  // Note: source_frame_ is inherited from MapvizPlugin (protected).
  // Access is synchronized via waypoints_mutex_ between the callback and
  // render threads.
  rclcpp::Time stamp_;

  void connectCallback(const std::string& topic, const rmw_qos_profile_t& qos);
  void waypointListCallback(
      const mavros_msgs::msg::WaypointList::SharedPtr msg);

  void DrawWaypoint(const TransformedWaypoint& wp, double scale);
  void DrawCurrentWaypointHighlight(const TransformedWaypoint& wp,
                                    double scale);
  void DrawWaypointConnections(
      const std::vector<TransformedWaypoint>& waypoints);
};

}  // namespace mapviz_mavros_plugins

#endif  // MAPVIZ_MAVROS_PLUGINS__WAYPOINT_LIST_PLUGIN_H_
